### ISSUE TITLE
Models are offline

### ISSUE THREAD

**Issue by onemenzel** [bclavie/edubert#1]
Hello,

I'm interested in using EduBERT to analyze educational forum discourse generated in a research project. However, the links provided in this project are offline. The message below shows up when I try to download them. I'd very much appreciate if you'd could look into that.

Best regards

```xml
<Error>
  <Code>UserProjectAccountProblem</Code>
  <Message>
    The project to be billed is associated with a closed billing account.
  </Message>
  <Details>
    The billing account for the owning project is disabled in state closed
  </Details>
</Error>
```

**Comment by onemenzel** [comment]
Maybe you could upload them as a public model to huggingface as they are using HF's transformers library anyway.

**Comment by bclavie** [comment]
Hi there -- very sorry for replying so late, I missed this issue. Will upload to HF soon, though I think it's time for EduBERT to be replaced by more efficient approaches (EduDeBERTa-V3 comes to mind)

**Comment by bclavie** [comment]
After an unbelievably long back-and-forth with Google Support, the links are back up, and the models are finally (shamefully, and utterly late) uploaded to HuggingFace: https://huggingface.co/bclavie/distiledubert and https://huggingface.co/bclavie/edubert.
